# Generated by Django 5.0.6 on 2024-06-25 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_App', '0002_alter_recipe_recipe_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
