# Generated by Django 5.0.6 on 2024-06-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_App', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
