# Generated by Django 5.0.6 on 2024-06-25 11:05

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_App', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=tinymce.models.HTMLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=tinymce.models.HTMLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=tinymce.models.HTMLField(max_length=700),
        ),
    ]
