# Generated by Django 5.0.6 on 2024-06-25 12:16

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_App', '0007_alter_recipe_description_alter_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=tinymce.models.HTMLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=tinymce.models.HTMLField(max_length=2000),
        ),
    ]
